### ISSUE TITLE
Add Video subtitles

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-resources#6]

**Comment by woshilapin** [comment]
I added the subtitles in the `/presentations/` folder.  I wonder if it would not be better to create a directory for all the files concerning this presentation (5 files)?  I could do the same for OpenDataDay (6 files).  I can do it and then close this issue.

I also have the video file but git doesn't like the big files; therefore, I've put a readme file that contains the Youtube link to the video.

**Comment by teolemon** [comment]
agreed

**Comment by woshilapin** [comment]
Done, therefore, I close the issue.
